Changed the binutils install script. Now it uses getopts and can also build the binary utilities automatically.
Pertains to ticket #29

diff --git a/src/acbinutils/acbingen.sh.in b/src/acbinutils/acbingen.sh.in
--- a/src/acbinutils/acbingen.sh.in
+++ b/src/acbinutils/acbingen.sh.in
@@ -7,14 +7,18 @@
 me=`echo "$0" | sed -e 's,.*/,,'`
 
 usage="\
-Usage: $0 [options] <archc source file> <architecture name>
+Usage: $0 [options] <model-file>
 
-Create binutils target source files and copy them to the binutils tree.
+Create binary utilities source files and optionally build them.
 
 Options:
-  -c, --create-only  only create the files, do not copy to binutils tree
-  -h, --help         print this help
-  -v, --version      print version number
+  -a<name>   sets the architecture name (if ommitted, it defaults to 
+             <model-file> without the extension
+  -i<dir>    build and install the binary utilities in directory <dir>
+             NOTE: <dir> -MUST- be an absolute path
+  -c         only create the files, do not copy to binutils tree
+  -h         print this help
+  -v         print version number
 
 Report bugs and patches to ArchC Team."
 
@@ -22,39 +26,45 @@ version="\
 ArchC binutils generator script version @VERSION@"
 
 help="
-Try \`$me --help' for more information."
+Try \`$me -h for more information."
 
+ARCH_NAME=""
 CREATE_ONLY=0
+BINUTILS_INST_DIR=""
 PATCH_BINUTILS=1  #1 means to patch, 0 otherwise
+TEMP_DIR="acbingenbuilddir"
 
 # Parse command line
-while test $# -gt 0 ; do
-  case $1 in
-    --version | -v )
-       echo "$version" ; exit 0 ;;
-    --help | --h* | -h )
-       echo "$usage"; exit 0 ;;
-    --create-only | -c )
-       CREATE_ONLY=1; shift; break ;;  
-#    -- )     # Stop option processing
-#       shift; break ;;
-    -* )
-       echo "$me: invalid option $1$help"
+while getopts  ":hvca:i:" flag
+do
+  case $flag in
+    h) echo "$usage"; exit 0 ;;
+    v) echo "$version" ; exit 0 ;;
+    c) CREATE_ONLY=1 ;;
+    a) ARCH_NAME="$OPTARG" ;;
+    i) BINUTILS_INST_DIR="$OPTARG" ;;
+    *) echo "$me: invalid option $help"
        exit 1 ;;
-    * )
-       break ;;
   esac
 done
+shift $(($OPTIND - 1))
 
 case $# in
- 0 | 1) echo "$me: missing argument$help" >&2
-    exit 1;;
- 2 | 3) ;;
- *) echo "$me: too many arguments$help" >&2
-    exit 1;;
+ 0 ) echo "No model file specified"
+     exit 1 ;;
+ 1 ) MODEL_FILE=$1 ;;
+ * ) echo "Too many arguments"
+     exit 1;;
 esac
 
-ARCH_NAME=$2
+if [ ! -f $MODEL_FILE ]; then
+  echo "File does not exist: $MODEL_FILE"
+  exit 1
+fi
+
+if [ -z "$ARCH_NAME" ]; then
+  ARCH_NAME=`echo "$MODEL_FILE" | sed -e "s/\..*$//"`
+fi
 
 ARCH_INVALID_CHAR=`echo "$2" | sed -e 's/[a-zA-Z][_a-zA-Z0-9]*//'`
 
@@ -89,8 +99,8 @@ if [ "$CREATE_ONLY" -eq 0 ]; then
   $BINUTILS_DIR/config.sub ${ARCH_NAME}-elf > /dev/null 2>&1
   if [ $? -eq 0 ]; then
     echo "==================="
-    echo "asmgen.sh has detected that your Binutils distribution already uses the"
-    echo "architecture name '${ARCH_NAME}'."
+    echo "It has been detected that your Binutils distribution already uses"
+    echo "the architecture name '${ARCH_NAME}'."
     echo
     echo "It is not recommended to continue if you have not set it by yourself."
 #  echo "If you continue, the Binutils files will not be patched."
@@ -106,14 +116,17 @@ if [ "$CREATE_ONLY" -eq 0 ]; then
 fi
 
 # creates binutils directory tree (if none was built)
-cp -rf @pkgdatadir@/binutils .
+mkdir -p $TEMP_DIR
+[ $? -ne 0 ] && exit $?
+cp -rf @pkgdatadir@/binutils ${TEMP_DIR}/
 
 
-# executes acasm to generate the files in the binutils tree
+# generate the files in the binutils tree
 echo "Generating machine dependent code..."
-@bindir@/bmdsfg $1 -a${ARCH_NAME}
+@bindir@/bmdsfg $MODEL_FILE -a${ARCH_NAME}
 [ $? -ne 0 ] && exit $?
 
+cd $TEMP_DIR
 
 # change the name of template files
 m4 -P defines.m4 binutils/ld/emulparams/xxxxxelf.sh > binutils/ld/emulparams/${ARCH_NAME}elf.sh
@@ -131,9 +144,6 @@ if [ "$CREATE_ONLY" -ne 0 ]; then
   echo
   exit 0
 fi
-
-# check if we need to patch the files
-#$BINUTILS_DIR/config.sub ${ARCH_NAME}-elf > /dev/null 2>&1
 
 if [ "$PATCH_BINUTILS" -ne 0 ]; then
 # applies the patch 
@@ -182,5 +192,19 @@ do
   [ $? -ne 0 ] && exit $?
 done
 
+if [ ! -z ${BINUTILS_INST_DIR} ]; then
+  echo "Installing the binary utilities..."
+ 
+  mkdir -p build
+  cd build
+  $BINUTILS_DIR/configure --target=${ARCH_NAME}-elf --prefix=`pwd` --bindir=${BINUTILS_INST_DIR}
+  [ $? -ne 0 ] && exit $?
+  make 
+  [ $? -ne 0 ] && exit $?
+  make install
+  [ $? -ne 0 ] && exit $?
+fi
+
 echo "All done successfully."
 echo
+
