Merged archc-newbingen-branch changes 294:453 into archc trunk

diff --git a/src/acbinutils/acbingen.sh.in b/src/acbinutils/acbingen.sh.in
--- a/src/acbinutils/acbingen.sh.in
+++ b/src/acbinutils/acbingen.sh.in
@@ -13,7 +13,7 @@ Create binary utilities source files and optionally build them.
 
 Options:
   -a<name>   sets the architecture name (if ommitted, it defaults to 
-             <model-file> without the extension
+             <model-file> without the extension)
   -i<dir>    build and install the binary utilities in directory <dir>
              NOTE: <dir> -MUST- be an absolute path
   -c         only create the files, do not copy to binutils tree
@@ -32,6 +32,7 @@ ARCH_NAME=""
 CREATE_ONLY=0
 BINUTILS_INST_DIR=""
 PATCH_BINUTILS=1  #1 means to patch, 0 otherwise
+PATCH_GDB=1  #1 means to patch, 0 otherwise
 TEMP_DIR="acbingenbuilddir"
 
 # Parse command line
@@ -128,6 +129,20 @@ echo "Generating machine dependent code..."
 
 cd $TEMP_DIR
 
+# copy 'modifiers' file into the directory
+if [ -f ../modifiers ]; then
+  cp -f ../modifiers .
+else
+  touch modifiers
+fi
+
+# copy 'defines_gdb' file into the directory
+if [ -f ../defines_gdb ]; then
+  cp -f ../defines_gdb .
+else
+  touch defines_gdb
+fi
+
 # change the name of template files
 m4 -P defines.m4 binutils/ld/emulparams/xxxxxelf.sh > binutils/ld/emulparams/${ARCH_NAME}elf.sh
 m4 -P defines.m4 binutils/include/opcode/xxxxx.h > binutils/include/opcode/${ARCH_NAME}.h
@@ -138,6 +153,20 @@ m4 -P defines.m4 binutils/opcodes/xxxxx-dis.c > binutils/opcodes/${ARCH_NAME}-di
 m4 -P defines.m4 binutils/include/elf/xxxxx.h > binutils/include/elf/${ARCH_NAME}.h
 m4 -P defines.m4 binutils/bfd/elf32-xxxxx.c > binutils/bfd/elf32-${ARCH_NAME}.c
 m4 -P defines.m4 binutils/gas/config/tc-xxxxx.c > binutils/gas/config/tc-${ARCH_NAME}.c
+m4 -P defines.m4 binutils/include/share-xxxxx.h > binutils/include/share-${ARCH_NAME}.h
+m4 -P defines.m4 binutils/bfd/share-xxxxx.c > binutils/bfd/share-${ARCH_NAME}.c
+
+# Check if 'modifiers' is syntatically valid
+# ATTENTION: sync with bfd/share-xxxxx.c
+if [ -f ../modifiers ]; then
+  echo "#include \"binutils/include/share-"${ARCH_NAME}".h\"" > temp_mod.c
+  echo "#define ac_modifier_encode(modifier) void modifier_ ##modifier ## _encode(mod_parms *reloc)" >> temp_mod.c
+  echo "#define ac_modifier_decode(modifier) void modifier_ ##modifier ## _decode(mod_parms *reloc)" >> temp_mod.c
+  echo "#include \"../modifiers\"" >> temp_mod.c
+  gcc -c -otemp_mod.o temp_mod.c
+  [ $? -ne 0 ] && exit $?
+  rm -f temp_mod.o temp_mod.c
+fi
 
 
 if [ "$CREATE_ONLY" -ne 0 ]; then
@@ -145,6 +174,83 @@ if [ "$CREATE_ONLY" -ne 0 ]; then
   echo
   exit 0
 fi
+
+
+if [ -z "$GDB_PATH" ]; then
+  GDB_PATH=`grep GDB_PATH @sysconfdir@/archc.conf | cut -d = -f2`
+  GDB_PATH=`echo $GDB_PATH`
+  
+#  if [ -z "$GDB_PATH" ]; then
+#    echo "GDB_PATH environment variable not set"
+#    exit 1
+#  fi 
+fi
+
+
+# check for '/' at the end and take it out
+GDB_DIR=`echo "$GDB_PATH" | sed -e 's/\/$//'`
+
+if [ ! -z ${GDB_DIR} ]; then
+  FILES_TO_PATCH_GDB="@patchfilesgdb@" 
+  FILES_TO_COPY_GDB="@copyfilesgdb@"
+
+  if [ "$CREATE_ONLY" -eq 0 ]; then
+  # tell the user if the architecture name already exists in Gdb
+    $GDB_DIR/config.sub ${ARCH_NAME}-elf > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+      echo "==================="
+      echo "It has been detected that your Gdb distribution already uses"
+      echo "the architecture name '${ARCH_NAME}'."
+      echo
+      echo "It is not recommended to continue if you have not set it by yourself."
+  #  echo "If you continue, the Gdb files will not be patched."
+      echo "==================="
+      echo
+      read -e -p "Do you wish to continue? (y) -> " USER_ANSWER; : ${USER_ANSWER:="y"}
+      echo
+      case $USER_ANSWER in 
+          y | yes | Y | YES) PATCH_GDB=0; break;;
+          * ) echo "Quitting ..."; echo; exit 1;;
+      esac
+    fi
+  fi
+fi
+
+# creates gdb directory tree (if none was built)
+cd ..
+TEMP_DIR="acbingenbuilddir"
+mkdir -p $TEMP_DIR
+[ $? -ne 0 ] && exit $?
+cp -rf @pkgdatadir@/gdb ${TEMP_DIR}/
+
+
+# generate the files in the gdb tree
+echo "Generating machine dependent code..."
+@bindir@/bmdsfg $MODEL_FILE -a${ARCH_NAME}
+[ $? -ne 0 ] && exit $?
+
+cd $TEMP_DIR
+mkdir -p gdb/gdb/config/${ARCH_NAME}
+
+# change the name of template files
+m4 -P defines.m4 gdb/include/opcode/xxxxx.h > gdb/include/opcode/${ARCH_NAME}.h
+m4 -P defines.m4 gdb/bfd/cpu-xxxxx.c > gdb/bfd/cpu-${ARCH_NAME}.c
+m4 -P defines.m4 gdb/opcodes/xxxxx-opc.c > gdb/opcodes/${ARCH_NAME}-opc.c
+m4 -P defines.m4 gdb/opcodes/xxxxx-dis.c > gdb/opcodes/${ARCH_NAME}-dis.c
+m4 -P defines.m4 gdb/include/elf/xxxxx.h > gdb/include/elf/${ARCH_NAME}.h
+m4 -P defines.m4 gdb/bfd/elf32-xxxxx.c > gdb/bfd/elf32-${ARCH_NAME}.c
+m4 -P defines.m4 gdb/gdb/xxxxx-tdep.c > gdb/gdb/${ARCH_NAME}-tdep.c
+m4 -P defines.m4 gdb/gdb/config/xxxxx/xxxxx.mt > gdb/gdb/config/${ARCH_NAME}/${ARCH_NAME}.mt
+m4 -P defines.m4 gdb/include/share-xxxxx.h > gdb/include/share-${ARCH_NAME}.h
+m4 -P defines.m4 gdb/bfd/share-xxxxx.c > gdb/bfd/share-${ARCH_NAME}.c
+
+
+if [ "$CREATE_ONLY" -ne 0 ]; then
+  echo "Done. No files copied."
+  echo
+  exit 0
+fi
+
 
 if [ "$PATCH_BINUTILS" -ne 0 ]; then
 # applies the patch 
@@ -193,6 +299,58 @@ do
   [ $? -ne 0 ] && exit $?
 done
 
+
+if [ ! -z ${GDB_DIR} ]; then
+  if [ "$PATCH_GDB" -ne 0 ]; then
+  # applies the patch 
+      echo "Patching... "
+      for file in $FILES_TO_PATCH_GDB
+      do
+      
+        if [ ! -f "$GDB_DIR/$file" ]; then
+
+	      if [ $file = "gdb/configure.tgt" ]; then
+  	        # Starting from 2.16, gdb uses configure.tgt
+	        # For compatibility with older versions, redirect to 'configure'
+	        file="gdb/configure"
+	        cp -f gdb/gdb/configure.tgt.sed gdb/gdb/configure.sed > /dev/null 2>&1
+	      else           	  
+      	        echo "Source file $file not found."
+  	        exit 1
+          fi
+        fi
+
+    # creates a backup
+        mv -f $GDB_DIR/$file $GDB_DIR/$file.bkp > /dev/null 2>&1
+        if [ $? -ne 0 ]; then
+	    echo "Cannot move file $file."
+	    exit 1
+        fi
+
+        sed s/xxxxx/${ARCH_NAME}/g gdb/$file.sed > gdb/$file.sed2
+        sed -f gdb/$file.sed2 $GDB_DIR/$file.bkp > $GDB_DIR/$file
+  
+      done
+   
+      chmod a+x $GDB_DIR/config.sub
+      chmod a+x $GDB_DIR/bfd/config.bfd
+
+  else
+      echo "Skipping patching..."
+  fi
+
+  # copies the generated files into gdb tree
+  mkdir -p $GDB_DIR/gdb/config/${ARCH_NAME}
+  echo "Copying files to gdb source tree..."
+  for file in $FILES_TO_COPY_GDB
+  do
+    cpfile=`echo "$file" | sed -e "s/xxxxx/${ARCH_NAME}/g"`
+    cp -f gdb/${cpfile} $GDB_DIR/${cpfile}
+    [ $? -ne 0 ] && exit $?
+  done
+fi
+
+
 if [ ! -z ${BINUTILS_INST_DIR} ]; then
   echo "Installing the binary utilities..."
  
@@ -204,6 +362,19 @@ if [ ! -z ${BINUTILS_INST_DIR} ]; then
   [ $? -ne 0 ] && exit $?
   make install
   [ $? -ne 0 ] && exit $?
+
+  if [ ! -z ${GDB_DIR} ]; then
+    cd ..
+    mkdir -p build_gdb
+    cd build_gdb
+    $GDB_DIR/configure --target=${ARCH_NAME}-elf --prefix=`pwd` --bindir=${BINUTILS_INST_DIR}
+    [ $? -ne 0 ] && exit $?
+    make 
+    [ $? -ne 0 ] && exit $?
+    make install
+    [ $? -ne 0 ] && exit $?
+  fi
+
 fi
 
 echo "All done successfully."
